### ISSUE TITLE
Just questions about your code, to understand it better

### ISSUE THREAD

**Issue by Yirmeyah-d** [dazdndcunfusd/OcamlKMP#1]
Hi Aaron,

I wanted to ask you a bunch of question about your KMP implementation in OCAML, i wanted to know how it works.
Does your code search for each pattern indicated in a read text file, if it's on a given text and return for each pattern found their index position (which is the line in the text file) and their position in the given text?
For exemple here a text file with those patterns:
at
gat
tt
aca

And the given text with those patterns:
gatgattaca

Could it return something like that ?
0 1
1 0
3 1
4 0
5 2
7 3

**Comment by Yirmeyah-d** [comment]
Hi Aaron,

I ask you those question but it was before testing your code...Now that i understand a little better what it does, i wanted to know if there is a way to do the same work but for a bunch of patterns, not only 1 pattern ? For example let's say i had those patterns:
at
gat
tt
aca

And i wanted to know if they are in this text :gatgattaca
So the output will be like :

pattern 1 found at characters 2, 5
pattern 2 found at characters 1, 4
pattern 3 found at characters 5
pattern 4 found at characters 8

How can i do something like this by using your code ?
Can you help me please ?

> Hi Aaron,
> 
> I wanted to ask you a bunch of question about your KMP implementation in OCAML, i wanted to know how it works.
> Does your code search for each pattern indicated in a read text file, if it's on a given text and return for each pattern found their index position (which is the line in the text file) and their position in the given text?
> For exemple here a text file with those patterns:
> at
> gat
> tt
> aca
> 
> And the given text with those patterns:
> gatgattaca
> 
> Could it return something like that ?
> 0 1
> 1 0
> 3 1
> 4 0
> 5 2
> 7 3

**Comment by aaron-loz** [comment]
Hi,

It is possible, mainly by inputting an argument for how many patterns there
would be to look at, and creating a function that reads the pattern and
recursively runs itself that number of times, outputting for each argument.
I am currently working on a different, non-functional project and haven't
touched the code since, but it should be simple to implement as a wrapper
over the core code.

Good luck!
Aaron

**Comment by Yirmerah** [comment]
Hi,

But how can i make the reading file function, read all the line of the text file and not only the first line ?

**Comment by Yirmerah** [comment]
Hi,
How did you manage to get execution time ?
